services:
  serverstatus-client:
    image: cppla/serverstatus:client
    container_name: serverstatus-client
    restart: unless-stopped
    network_mode: host
    pid: host
    environment:
      - SERVER=${SERVER:-127.0.0.1}
      - USER=${USER:-s01}
      - PASSWORD=${PASSWORD:-USER_DEFAULT_PASSWORD}
      - PORT=${PORT:-35601}
      - INTERVAL=${INTERVAL:-1}
