services:
  serverstatus:
    image: aoomee/serverstatus-refined:latest
    container_name: serverstatus-server
    restart: unless-stopped
    ports:
      - 8080:80
      - 35601:35601
    volumes:
      - ./server/config.json:/app/config/config.json
      - ./web/json:/app/data
    environment:
      ADMIN_TOKEN: "${ADMIN_TOKEN:-}"
