services:
  serverstatus-client:
    image: cppla/serverstatus:client
    container_name: serverstatus-client
    restart: unless-stopped
    network_mode: host
    pid: host
    environment:
      - SERVER=127.0.0.1                # 改成你服务端的 IP
      - USER=s01                        # 改成服务端配置里对应的用户名
      - PASSWORD=USER_DEFAULT_PASSWORD  # 改成服务端配置里对应的密码
