services:
  serverstatus:
    image: ghcr.io/aoomee/serverstatus-refined:latest
    container_name: serverstatus-server
    restart: unless-stopped
    ports:
      - "16888:80"
      - "35601:35601"
    volumes:
      - ./data:/app/data
    environment:
      - ADMIN_TOKEN=your-password-here
