version: '3'

services:
  serverstatus-client:
    image: cppla/serverstatus:client
    container_name: serverstatus-client
    restart: unless-stopped
    network_mode: host
    pid: host
    environment:
      - SERVER=127.0.0.1
      - USER=s01
      - PASSWORD=USER_DEFAULT_PASSWORD
